In [43]:
from pybaseball import statcast
import pandas as pd
import numpy as np

In [9]:
for col in df.columns:
    print(col)

pitch_type
game_date
release_speed
release_pos_x
release_pos_z
player_name
batter
pitcher
events
description
spin_dir
spin_rate_deprecated
break_angle_deprecated
break_length_deprecated
zone
des
game_type
stand
p_throws
home_team
away_team
type
hit_location
bb_type
balls
strikes
game_year
pfx_x
pfx_z
plate_x
plate_z
on_3b
on_2b
on_1b
outs_when_up
inning
inning_topbot
hc_x
hc_y
tfs_deprecated
tfs_zulu_deprecated
umpire
sv_id
vx0
vy0
vz0
ax
ay
az
sz_top
sz_bot
hit_distance_sc
launch_speed
launch_angle
effective_speed
release_spin_rate
release_extension
game_pk
fielder_2
fielder_3
fielder_4
fielder_5
fielder_6
fielder_7
fielder_8
fielder_9
release_pos_y
estimated_ba_using_speedangle
estimated_woba_using_speedangle
woba_value
woba_denom
babip_value
iso_value
launch_speed_angle
at_bat_number
pitch_number
pitch_name
home_score
away_score
bat_score
fld_score
post_away_score
post_home_score
post_bat_score
post_fld_score
if_fielding_alignment
of_fielding_alignment
spin_axis
delta_home_win_exp
delta_run_exp
bat_speed
swing_length
estimated_slg_using_speedangle
delta_pitcher_run_exp
hyper_speed
home_score_diff
bat_score_diff
home_win_exp
bat_win_exp
age_pit_legacy
age_bat_legacy
age_pit
age_bat
n_thruorder_pitcher
n_priorpa_thisgame_player_at_bat
pitcher_days_since_prev_game
batter_days_since_prev_game
pitcher_days_until_next_game
batter_days_until_next_game
api_break_z_with_gravity
api_break_x_arm
api_break_x_batter_in
arm_angle
attack_angle
attack_direction
swing_path_tilt
intercept_ball_minus_batter_pos_x_inches
intercept_ball_minus_batter_pos_y_inches

In [ ]:
def get_transformed_data(start_dt, end_dt):
    df = statcast(start_dt = start_dt, end_dt = end_dt).sort_values(by=['game_date', 'at_bat_number'])
    play_results = df['events']
    pitch_results = df['description']
    home_team_win_target = (
        df.sort_values(['home_team', 'game_date', 'at_bat_number'])
        .groupby(['home_team', 'game_date'])['home_win_exp']
        .last()
        .pipe(np.round)
        )
    
    res_dict = {
        'Context': None,
        'Play by Play': None,
        'Pitch_target' : None,
        'Result_target' : None,
        'Game_target' : None
    }

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
2442,FF,2025-05-01,91.4,-1.37,5.14,"Lively, Ben",666397,594902,field_out,hit_into_play,...,1,1.71,1.08,-1.08,38.4,15.849379,5.163524,37.579678,41.961883,28.489756
2473,FF,2025-05-01,92.2,-1.41,5.15,"Lively, Ben",666397,594902,NaN,foul,...,1,1.36,0.94,-0.94,40.9,5.155893,3.167203,45.518316,33.153286,28.449989
2561,SI,2025-05-01,91.6,-1.43,5.12,"Lively, Ben",666397,594902,NaN,foul,...,1,1.88,1.21,-1.21,40.5,-2.828276,17.944346,51.351635,24.45473,24.043783
2651,SI,2025-05-01,91.7,-1.58,5.02,"Lively, Ben",666397,594902,NaN,ball,...,1,1.9,1.48,-1.48,34.2,<NA>,<NA>,<NA>,<NA>,<NA>
2739,CU,2025-05-01,77.3,-1.51,5.33,"Lively, Ben",666397,594902,NaN,ball,...,1,4.16,-0.64,0.64,43.7,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3571,FF,2025-05-10,94.9,-1.58,5.7,"Pagán, Emilio",701358,641941,NaN,ball,...,1,1.05,0.52,0.52,42.1,<NA>,<NA>,<NA>,<NA>,<NA>
2763,FF,2025-05-10,95.6,-1.54,5.59,"Pagán, Emilio",665161,641941,double,hit_into_play,...,1,0.88,0.82,0.82,42.0,15.84212,-18.354518,35.431564,31.574918,37.307329
2545,FC,2025-05-10,88.1,-1.82,5.51,"Pagán, Emilio",663898,641941,strikeout,swinging_strike,...,1,2.63,-0.46,-0.46,45.4,19.723582,-24.68105,33.068368,42.560007,48.486111
2582,FF,2025-05-10,94.8,-1.63,5.58,"Pagán, Emilio",663898,641941,NaN,foul,...,1,0.91,0.37,0.37,41.1,7.408551,-7.609833,39.478588,42.055248,28.518635
2669,FC,2025-05-10,86.7,-1.77,5.62,"Pagán, Emilio",663898,641941,NaN,swinging_strike,...,1,2.74,-0.5,-0.5,43.0,23.816753,-30.979234,32.148056,38.404247,47.935558

In [27]:
df.select_dtypes(str)

,pitch_type,game_date,player_name,events,description,des,game_type,stand,p_throws,home_team,away_team,type,bb_type,inning_topbot,pitch_name,if_fielding_alignment,of_fielding_alignment
2333,FF,2025-05-10,"Jackson, Luke",strikeout,called_strike,Trey Sweeney called out on strikes.,R,L,R,DET,TEX,S,NaN,Bot,4-Seam Fastball,Infield shade,Standard
2403,FF,2025-05-10,"Jackson, Luke",NaN,foul,Foul,R,L,R,DET,TEX,S,NaN,Bot,4-Seam Fastball,Infield shade,Standard
2534,SL,2025-05-10,"Jackson, Luke",NaN,foul,Foul,R,L,R,DET,TEX,S,NaN,Bot,Slider,Infield shade,Standard
2636,FF,2025-05-10,"Jackson, Luke",NaN,ball,Ball,R,L,R,DET,TEX,B,NaN,Bot,4-Seam Fastball,Infield shade,Standard
2731,SL,2025-05-10,"Jackson, Luke",NaN,foul_tip,Foul Tip,R,L,R,DET,TEX,S,NaN,Bot,Slider,Infield shade,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2642,SL,2025-05-01,"Burke, Sean",NaN,called_strike,Called Strike,R,L,R,CWS,MIL,S,NaN,Top,Slider,Standard,Standard
2730,SL,2025-05-01,"Burke, Sean",NaN,ball,Ball,R,L,R,CWS,MIL,B,NaN,Top,Slider,Standard,Standard
2830,FF,2025-05-01,"Burke, Sean",NaN,ball,Ball,R,L,R,CWS,MIL,B,NaN,Top,4-Seam Fastball,Standard,Standard
2921,FF,2025-05-01,"Burke, Sean",NaN,foul,Foul,R,L,R,CWS,MIL,S,NaN,Top,4-Seam Fastball,Standard,Standard
3012,FF,2025-05-01,"Burke, Sean",NaN,ball,Ball,R,L,R,CWS,MIL,B,NaN,Top,4-Seam Fastball,Standard,Standard

In [58]:
result

home_team  game_date
ATH        2025-05-05    1.0
           2025-05-06    0.0
           2025-05-07    0.0
           2025-05-09    0.0
           2025-05-10    1.0
                        ...
TOR        2025-05-04    0.0
WSH        2025-05-06    1.0
           2025-05-07    0.0
           2025-05-09    0.0
           2025-05-10    0.0
Name: home_win_exp, Length: 131, dtype: Float64

In [ ]:
df.sort_values(['home_team', 'game_date', 'at_bat_number']).groupby(['home_team', 'game_date'])['home_score_diff'].last()

<IntegerArray>
[  0,  -2,  -1,  -8,   4,  -7,   1,  -6,   2,  -3,   3,  -4,  -5,   5,   7,
  -9,   8,   6, -21,  10, -12, -10,   9]
Length: 23, dtype: Int64

In [38]:
for col in df.columns:
    print(col)

pitch_type
game_date
release_speed
release_pos_x
release_pos_z
player_name
batter
pitcher
events
description
spin_dir
spin_rate_deprecated
break_angle_deprecated
break_length_deprecated
zone
des
game_type
stand
p_throws
home_team
away_team
type
hit_location
bb_type
balls
strikes
game_year
pfx_x
pfx_z
plate_x
plate_z
on_3b
on_2b
on_1b
outs_when_up
inning
inning_topbot
hc_x
hc_y
tfs_deprecated
tfs_zulu_deprecated
umpire
sv_id
vx0
vy0
vz0
ax
ay
az
sz_top
sz_bot
hit_distance_sc
launch_speed
launch_angle
effective_speed
release_spin_rate
release_extension
game_pk
fielder_2
fielder_3
fielder_4
fielder_5
fielder_6
fielder_7
fielder_8
fielder_9
release_pos_y
estimated_ba_using_speedangle
estimated_woba_using_speedangle
woba_value
woba_denom
babip_value
iso_value
launch_speed_angle
at_bat_number
pitch_number
pitch_name
home_score
away_score
bat_score
fld_score
post_away_score
post_home_score
post_bat_score
post_fld_score
if_fielding_alignment
of_fielding_alignment
spin_axis
delta_home_win_exp
delta_run_exp
bat_speed
swing_length
estimated_slg_using_speedangle
delta_pitcher_run_exp
hyper_speed
home_score_diff
bat_score_diff
home_win_exp
bat_win_exp
age_pit_legacy
age_bat_legacy
age_pit
age_bat
n_thruorder_pitcher
n_priorpa_thisgame_player_at_bat
pitcher_days_since_prev_game
batter_days_since_prev_game
pitcher_days_until_next_game
batter_days_until_next_game
api_break_z_with_gravity
api_break_x_arm
api_break_x_batter_in
arm_angle
attack_angle
attack_direction
swing_path_tilt
intercept_ball_minus_batter_pos_x_inches
intercept_ball_minus_batter_pos_y_inches